/*
 * Este es un proyecto creado por el Grupo #4 de POO.
 * El funcionamiento de este es calcular el IMC de una persona
 * Y a la vez muestra informacion sobre el IMC y tips para ejercitarse.
 */
package imc;


public class IMCVentana5 extends javax.swing.JFrame {

    /**
     * Creacion del nuevo form IMCVentana5
     */
    public IMCVentana5() {
        initComponents();
        
     /**
     * Este codigo es para que al momento de mostrar la ventana de informacion
     * no se pueda maximizar.
     */
        
        setLocationRelativeTo (null);
        setResizable (false);
        setTitle("Calculadora de IMC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Antes de comenzar la rutina de ejercicios es necesario correr\no montar en bici durante 10 minutos.\nTras esto puedes seguir la siguiente tabla de ejercicios.\nPara realizarlos correctamente lo más sencillo es mirar vídeos\nen Internet.\nEn Youtube se pueden encontrar cientos de vídeos explicativos para\ncada uno de los ejercicios.\nEstos son los más básicos, pero con el tiempo puedes ir incorporando\nmuchos otros. Entre ejercicio y ejercicio no\ndebes descansar más de dos minutos.\n\n- Sentadillas (3 series / 10 repeticiones)\nPonte de pie con los pies en línea recta respecto a tus hombros,\nempieza a bajar tu cadera como si fueras a sentarte en una silla.\nAl doblar las rodillas los muslos deben llegar a estar paralelos al\nsuelo. Con el tiempo podrás hacer el ejercicio sujetando un peso con\nlos brazos delante del pecho.\n\n- Flexiones (3 series / 12 repeticiones)\nApoya las manos separadas del ancho de los hombros y alineadas\ncon estos. Ahora baja y sube el pecho manteniendo las piernas\nestiradas. Pese a ser un ejercicio que todos hemos practicado\nen el colegio es más duro de lo que parece.\nSi estás empezando con el entrenamiento puedes “hacer trampa” \napoyando las rodillas, pero procura hacer las flexiones\ncompletas en cuanto empieces a mejorar.\n\n- Zancadas (2 series / 14 repeticiones)\nLas zancadas son uno de los ejercicios más completos y\nestán presentes en todas las rutinas de entrenamiento.\nMantén una posición de semi-cuclillas con tus manos en la\ncadera, y adelanta alternativamente una y otra pierna. \nLa pierna adelantada nunca debe superar el ángulo de 90 grados y el \ntalón de la pierna desplazada no debe despegarse del suelo. Con el\ntiempo puedes hacer este ejercicio sujetando una mancuerna en cada\nmano.\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Cómo Debo entrenar?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMCVentana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMCVentana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMCVentana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMCVentana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMCVentana5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
